default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_app_development
  username: postgres
  password: Gayathri@123
  host: 127.0.0.1

test:
  <<: *default
  database: todo_app_test
  username: postgres
  password: Gayathri@123
  host: 127.0.0.1

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
